### PR TITLE
Remove hotlinked Google script: reduce # of queries, protect user privacy

### PR DESCRIPTION
**Pull request by alct**

### CODE REVIEW

**Comment by alct** [comment]
Note that the `./bootstrap/assets/js/vendor/jquery.min.js` file does not exist (so the [current fallback](https://github.com/astroidmail/astroidmail.github.io/blob/master/_includes/footer.html#L24) doesn't work). Depending on the way the website is built, this asset should be created either at the specified location or in a new, bootstrap-independent one.

**Comment by gauteh** [comment]
Thanks. @hugoroy: Do you have the chance to review this?

**Comment by hugoroy** [comment]
↪ Gaute Hope / juin 15, 2017 8:47:
> Thanks. @hugoroy: Do you have the chance to review this?

Hi! Sorry I'm swamped in work at the moment... and writing this from a
train, offline!

**Comment by gauteh** [comment]
Ok! Looks good, merged.

**Pull request merged**
